cmake_minimum_required(VERSION 3.20)
project(libnatkit VERSION 0.0
                  LANGUAGES C CXX)

if (NOT DEFINED LIBNATKIT_ESP_BUILD)
  set(LIBNATKIT_ESP_BUILD OFF CACHE BOOL "Build a subsection of libnatkit for ESP32 devices")
endif()

set(LIBNATKIT_PROJECT_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
set(LIBNATKIT_THIRD_PARTY_DIR ${LIBNATKIT_PROJECT_ROOT}/third-party)
set(LIBNATKIT_BUILD_ROOT ${CMAKE_CURRENT_BINARY_DIR})
set(LIBNATKIT_SCRIPTS_DIR ${LIBNATKIT_PROJECT_ROOT}/scripts)
set(LIBNATKIT_INSTALL_DIR ${LIBNATKIT_BUILD_ROOT})
set(LIBNATKIT_LIBRARY_INSTALL_DIR ${LIBNATKIT_INSTALL_DIR}/lib/Debug)
set(LIBNATKIT_INCLUDE_INSTALL_DIR ${LIBNATKIT_INSTALL_DIR}/include)
set(LIBNATKIT_BINARY_INSTALL_DIR ${LIBNATKIT_INSTALL_DIR}/bin)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
list(APPEND CMAKE_MODULE_PATH ${LIBNATKIT_PROJECT_ROOT}/cmake)

if(LIBNATKIT_ESP_BUILD)
  message("ESP32 Build")
  include(GNUInstallDirs)
elseif(WIN32)
  set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${LIBNATKIT_LIBRARY_INSTALL_DIR})
  set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${LIBNATKIT_BINARY_INSTALL_DIR})
  message("Detected OS is Windows")
elseif(UNIX)
  if (APPLE)
    message("Detected OS is MacOS")
  else()
    message("Detected OS is Linux")
  endif()
else()
  message(WARNING "Unsupported OS!")
endif()

if(LIBNATKIT_ESP_BUILD)
  message("ESP32 Compiler")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20")
elseif(MSVC)
  message("------------------ Compiler is MSVC ------------------")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D__msvc_cplusplus /std:c++20")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /std:c11")
  set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
  set(BUILD_SHARED_LIBS ON)
else()
message("------------------ Compiler is Something Else ------------------")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g3 -O0 -std=c++20")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g3 -O0")
  if (NOT APPLE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,--disable-new-dtags")
  endif()
endif()
set(CMAKE_VERBOSE_MAKEFILE ON)


include(ExternalProject)

#find_program(MEMORYCHECK_COMMAND valgrind)
#set(MEMORYCHECK_COMMAND_OPTIONS "--leak-check=full --error-exitcode=1")
if(NOT LIBNATKIT_ESP_BUILD)
  include(CTest)
endif()

if(UNIX)
  set(LIBNATKIT_LIBRARY_PREFIX "lib")
  if(APPLE)
    set(LIBNATKIT_DYNAMIC_LIBRARY_EXTENSION ".dylib")
    set(LIBNATKIT_STATIC_LIBRARY_EXTENSION ".a")
  else()
    set(LIBNATKIT_DYNAMIC_LIBRARY_EXTENSION ".so")
    set(LIBNATKIT_STATIC_LIBRARY_EXTENSION ".a")
  endif()
endif(UNIX)

if(WIN32)
  set(LIBNATKIT_DYNAMIC_LIBRARY_EXTENSION ".dll")
  set(LIBNATKIT_STATIC_LIBRARY_EXTENSION ".lib")
  set(LIBNATKIT_LIBRARY_PREFIX "")
endif(WIN32)

if(LIBNATKIT_ESP_BUILD)
elseif(WIN32)
  set(LIBRDKAFKA_SOURCE_DIR "${LIBNATKIT_BUILD_ROOT}/third-party/librdkafka")
	set(LIBRDKAFKA_BINARY_DIR "${CMAKE_BINARY_DIR}/archive/librdkafka")
  set(LIBRDKAFKA_INCLUDE_DIR ${LIBNATKIT_INCLUDE_INSTALL_DIR})
  set(LIBRDKAFKA_INCLUDE_INSTALL_DIR ${LIBNATKIT_INCLUDE_INSTALL_DIR}/librdkafka)
  set(LIBRDKAFKA_LIBRARY_DIR ${LIBNATKIT_LIBRARY_INSTALL_DIR})
	cmake_path(CONVERT ${LIBRDKAFKA_SOURCE_DIR} TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_SOURCE_DIR)
	cmake_path(CONVERT ${LIBRDKAFKA_SOURCE_DIR}/librdkafka.redist.2.2.0 TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_DOWNLOADED_SOURCE_DIR)
	cmake_path(CONVERT ${LIBRDKAFKA_INCLUDE_INSTALL_DIR} TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_INCLUDE_INSTALL_DIR)
  cmake_path(CONVERT ${LIBRDKAFKA_LIBRARY_DIR} TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_LIBRARY_DIR)
  cmake_path(CONVERT ${LIBRDKAFKA_BINARY_DIR} TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_BINARY_DIR)
	set(LIBRDKAFKA_CXX_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/librdkafkacpp${LIBNATKIT_STATIC_LIBRARY_EXTENSION}")
	set(LIBRDKAFKA_C_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/librdkafka${LIBNATKIT_STATIC_LIBRARY_EXTENSION}")

  set(LIBRDKAFKA_INSTALL_COMMAND "${LIBNATKIT_SCRIPTS_DIR}/install_librdkafka.ps1 ${WIN_LIBRDKAFKA_BINARY_DIR}")
  set(LIBRDKAFKA_INSTALL_ARGS "${WIN_LIBRDKAFKA_LIBRARY_DIR} ${WIN_LIBRDKAFKA_INCLUDE_INSTALL_DIR}")
  message("Installing librdkafka with the following command:")
  message("    ${LIBRDKAFKA_INSTALL_COMMAND} ${LIBRDKAFKA_INSTALL_ARGS}")
  execute_process(COMMAND powershell ${LIBRDKAFKA_INSTALL_COMMAND} ${LIBRDKAFKA_INSTALL_ARGS}
                  RESULT_VARIABLE LIBRDKAFKA_INSTALL_RESULT
                  OUTPUT_VARIABLE LIBRDKAFKA_INSTALL_RESULT)
  add_library(librdkafka-cxx STATIC IMPORTED)
  add_library(librdkafka-c STATIC IMPORTED)

else()
  set(LIBRDKAFKA_SOURCE_DIR "${LIBNATKIT_PROJECT_ROOT}/third-party/librdkafka")
	set(LIBRDKAFKA_BINARY_DIR "${CMAKE_BINARY_DIR}/librdkafka")
  set(LIBRDKAFKA_BUILD_DIR "${CMAKE_BINARY_DIR}/third-party/librdkafka")
  set(LIBRDKAFKA_INSTALL_DIR ${LIBNATKIT_INSTALL_DIR})
	set(LIBRDKAFKA_INCLUDE_DIR "${LIBRDKAFKA_INSTALL_DIR}/include")
	set(LIBRDKAFKA_LIBRARY_DIR "${LIBRDKAFKA_INSTALL_DIR}/lib")
	set(LIBRDKAFKA_CXX_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/${LIBNATKIT_LIBRARY_PREFIX}rdkafka++${LIBNATKIT_DYNAMIC_LIBRARY_EXTENSION}")
	set(LIBRDKAFKA_C_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/${LIBNATKIT_LIBRARY_PREFIX}rdkafka${LIBNATKIT_DYNAMIC_LIBRARY_EXTENSION}")

  execute_process(COMMAND ${LIBNATKIT_SCRIPTS_DIR}/install_librdkafka.sh ${LIBRDKAFKA_SOURCE_DIR} ${LIBRDKAFKA_BUILD_DIR} ${LIBRDKAFKA_INSTALL_DIR})

  add_library(librdkafka-cxx SHARED IMPORTED)
  add_library(librdkafka-c SHARED IMPORTED)
endif()


if(NOT LIBNATKIT_ESP_BUILD)
  message("librdkafka c++ is located at ${LIBRDKAFKA_CXX_LIBRARY}")
  message("librdkafka headers are located at ${LIBRDKAFKA_INCLUDE_DIR}")
  set_target_properties(librdkafka-cxx PROPERTIES
    IMPORTED_LOCATION ${LIBRDKAFKA_CXX_LIBRARY}
    INTERFACE_INCLUDE_DIRECTORIES ${LIBRDKAFKA_INCLUDE_DIR}
    )
    message("librdkafka c is located at ${LIBRDKAFKA_C_LIBRARY}")
  set_target_properties(librdkafka-c PROPERTIES
    IMPORTED_LOCATION ${LIBRDKAFKA_C_LIBRARY}
    INTERFACE_INCLUDE_DIRECTORIES ${LIBRDKAFKA_INCLUDE_DIR}
    )
  if (WIN32)
    set_target_properties(librdkafka-cxx PROPERTIES
      IMPORTED_IMPLIB ${LIBRDKAFKA_CXX_LIBRARY}
      IMPORTED_IMPLIB_DEBUG ${LIBRDKAFKA_CXX_LIBRARY}
    )
    set_target_properties(librdkafka-c PROPERTIES
      IMPORTED_IMPLIB ${LIBRDKAFKA_C_LIBRARY}
      IMPORTED_IMPLIB_DEBUG ${LIBRDKAFKA_C_LIBRARY}
    )
  endif()
endif()

add_library(nlohmann INTERFACE)
target_include_directories(nlohmann INTERFACE ${LIBNATKIT_THIRD_PARTY_DIR}/nlohmann/include)

include(ExternalProject)
#set(LIBNATKITCORE_SRC_DIR ${CMAKE_BINARY_DIR}/libnatkit-core-src)
set(LIBNATKITCORE_SRC_DIR ${LIBNATKIT_PROJECT_ROOT}/lib/libnatkit-core)
set(LIBNATKITCORE_BUILD_DIR ${CMAKE_BINARY_DIR}/libnatkit-core-build)
set(LIBNATKITCORE_LIBRARY ${LIBNATKITCORE_BUILD_DIR}/liblibnatkit-core${LIBNATKIT_DYNAMIC_LIBRARY_EXTENSION})
set(LIBNATKITCORE_INCLUDE ${LIBNATKITCORE_SRC_DIR}/include)
ExternalProject_Add(libnatkit-core-project
  #GIT_REPOSITORY    https://github.com/neuralbertatech/libnatkit-core
  #GIT_TAG           trunk
  #DOWNLOAD_DIR      ${LIBNATKITCORE_SRC_DIR}
  SOURCE_DIR        ${LIBNATKITCORE_SRC_DIR}
  BINARY_DIR        ${LIBNATKITCORE_BUILD_DIR}
  DOWNLOAD_COMMAND  ""
  CONFIGURE_COMMAND ${CMAKE_COMMAND} -S ${LIBNATKITCORE_SRC_DIR} -B ${LIBNATKITCORE_BUILD_DIR} -DSTANDARD_BUILD=ON
  BUILD_COMMAND     ${CMAKE_COMMAND} --build ${LIBNATKITCORE_BUILD_DIR}
  INSTALL_COMMAND   ""
  TEST_COMMAND      ""
  BYPRODUCTS        ${LIBNATKITCORE_INCLUDE}/libnatkit-core.hpp 
  BUILD_BYPRODUCTS  ${LIBNATKITCORE_LIBRARY}
)

add_library(libnatkit-core SHARED IMPORTED)
add_dependencies(libnatkit-core libnatkit-core-project)
target_include_directories(libnatkit-core INTERFACE
  $<BUILD_INTERFACE:${LIBNATKITCORE_INCLUDE}>
  $<INSTALL_INTERFACE:include>
)
if(WIN32)
  set_property(
    TARGET libnatkit-core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG
    )
  set_target_properties(libnatkit-core PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
    IMPORTED_LOCATION_DEBUG ${LIBNATKITCORE_BUILD_DIR}
  )
else()
  set_target_properties(libnatkit-core PROPERTIES IMPORTED_LOCATION ${LIBNATKITCORE_LIBRARY})
endif()

if(NOT LIBNATKIT_ESP_BUILD)
  include(AddMosquitto)

  if(BUILD_TESTING)
    enable_testing()
    include(AddGoogleTest)
  endif()
endif()

add_subdirectory(libnatkit)
