cmake_minimum_required(VERSION 3.20)
project(libnatkit VERSION 0.0
                  LANGUAGES C CXX)

set(PROJECT_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
set(BUILD_ROOT ${CMAKE_CURRENT_BINARY_DIR})
set(SCRIPTS_DIR ${PROJECT_ROOT}/scripts)
set(INSTALL_DIR ${BUILD_ROOT})
set(LIBRARY_INSTALL_DIR ${INSTALL_DIR}/lib)
set(INCLUDE_INSTALL_DIR ${INSTALL_DIR}/include)
set(BINARY_INSTALL_DIR ${INSTALL_DIR}/bin)
list(APPEND CMAKE_MODULE_PATH ${PROJECT_ROOT}/cmake)

if(WIN32)
  set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${LIBRARY_INSTALL_DIR})
  set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BINARY_INSTALL_DIR})
  message("Detected OS is Windows")
elseif(UNIX)
  if (APPLE)
    message("Detected OS is MacOS")
  else()
    message("Detected OS is Linux")
  endif()
else()
  message(WARNING "Unsupported OS!")
endif()

if(MSVC)
  message("------------------ Compiler is MSVC ------------------")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D__msvc_cplusplus /std:c++20")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /std:c11")
  set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
  set(BUILD_SHARED_LIBS ON)
else()
message("------------------ Compiler is Something Else ------------------")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g3 -O0")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g3 -O0")
endif()
set(CMAKE_VERBOSE_MAKEFILE ON)


include(ExternalProject)
include(CTest)

if(UNIX)
  set(DYNAMIC_LIBRARY_EXTENSION ".so")
  set(STATIC_LIBRARY_EXTENSION ".a")
  set(LIBRARY_PREFIX "lib")
endif(UNIX)

if(WIN32)
  set(DYNAMIC_LIBRARY_EXTENSION ".dll")
  set(STATIC_LIBRARY_EXTENSION ".lib")
  set(LIBRARY_PREFIX "")
endif(WIN32)


if(WIN32)
    set(LIBRDKAFKA_SOURCE_DIR "${PROJECT_ROOT}/third-party/librdkafka")
	set(LIBRDKAFKA_BINARY_DIR "${CMAKE_BINARY_DIR}/librdkafka")
	#set(LIBRDKAFKA_INSTALL_DIR "${LIBRDKAFKA_BINARY_DIR}/_install")
  set(LIBRDKAFKA_INSTALL_DIR ${INSTALL_DIR})
	cmake_path(CONVERT ${LIBRDKAFKA_SOURCE_DIR} TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_SOURCE_DIR)
	cmake_path(CONVERT ${LIBRDKAFKA_SOURCE_DIR}/librdkafka.redist.2.2.0 TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_DOWNLOADED_SOURCE_DIR)
	cmake_path(CONVERT ${LIBRDKAFKA_INSTALL_DIR} TO_NATIVE_PATH_LIST WIN_LIBRDKAFKA_INSTALL_DIR)
	set(LIBRDKAFKA_INCLUDE_DIR "${LIBRDKAFKA_INSTALL_DIR}/include")
	set(LIBRDKAFKA_LIBRARY_DIR "${LIBRDKAFKA_INSTALL_DIR}/lib")
	set(LIBRDKAFKA_CXX_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/${LIBRARY_PREFIX}rdkafka++${DYNAMIC_LIBRARY_EXTENSION}")
	set(LIBRDKAFKA_C_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/${LIBRARY_PREFIX}rdkafka${DYNAMIC_LIBRARY_EXTENSION}")

	ExternalProject_Add(librdkafka-module
	  GIT_REPOSITORY "https://github.com/confluentinc/librdkafka"
	  GIT_TAG v2.2.0
	  UPDATE_COMMAND ""
	  UPDATE_DISCONNECTED ON
	  DOWNLOAD_DIR "${LIBRDKAFKA_SOURCE_DIR}"
	  SOURCE_DIR "${LIBRDKAFKA_SOURCE_DIR}"
	  BINARY_DIR "${LIBRDKAFKA_BINARY_DIR}"
	  INSTALL_DIR "${LIBRDKAFKA_INSTALL_DIR}"
	  DOWNLOAD_COMMAND echo "${SCRIPTS_DIR}/download_librdkafka.bat ${WIN_LIBRDKAFKA_SOURCE_DIR} 2.2.0"
	  CONFIGURE_COMMAND ""
	  BUILD_COMMAND ""
	  INSTALL_COMMAND echo "${SCRIPTS_DIR}/install_librdkafka.bat ${WIN_LIBRDKAFKA_DOWNLOADED_SOURCE_DIR} ${WIN_LIBRDKAFKA_INSTALL_DIR}"
    BUILD_BYPRODUCTS ${LIBRDKAFKA_CXX_LIBRARY} ${LIBRDKAFKA_C_LIBRARY}
	  )
else()
    set(LIBRDKAFKA_SOURCE_DIR "${PROJECT_ROOT}/third-party/librdkafka")
	set(LIBRDKAFKA_BINARY_DIR "${CMAKE_BINARY_DIR}/librdkafka")
	#set(LIBRDKAFKA_INSTALL_DIR "${LIBRDKAFKA_BINARY_DIR}/_install")
  set(LIBRDKAFKA_INSTALL_DIR ${INSTALL_DIR})
	set(LIBRDKAFKA_INCLUDE_DIR "${LIBRDKAFKA_INSTALL_DIR}/include")
	set(LIBRDKAFKA_LIBRARY_DIR "${LIBRDKAFKA_INSTALL_DIR}/lib")
	set(LIBRDKAFKA_CXX_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/${LIBRARY_PREFIX}rdkafka++${DYNAMIC_LIBRARY_EXTENSION}")
	set(LIBRDKAFKA_C_LIBRARY "${LIBRDKAFKA_LIBRARY_DIR}/${LIBRARY_PREFIX}rdkafka${DYNAMIC_LIBRARY_EXTENSION}")
	ExternalProject_Add(librdkafka-module
	  GIT_REPOSITORY "https://github.com/confluentinc/librdkafka"
	  GIT_TAG v2.2.0
	  UPDATE_COMMAND ""
	  UPDATE_DISCONNECTED ON
	  SOURCE_DIR "${LIBRDKAFKA_SOURCE_DIR}"
	  BINARY_DIR "${LIBRDKAFKA_BINARY_DIR}"
	  INSTALL_DIR "${LIBRDKAFKA_INSTALL_DIR}"
	  CONFIGURE_COMMAND cd ${LIBRDKAFKA_SOURCE_DIR} && ./configure --install-deps --prefix=${LIBRDKAFKA_INSTALL_DIR}
	  BUILD_COMMAND make -C ${LIBRDKAFKA_SOURCE_DIR}
	  INSTALL_COMMAND make -C ${LIBRDKAFKA_SOURCE_DIR} install
    BUILD_BYPRODUCTS ${LIBRDKAFKA_CXX_LIBRARY} ${LIBRDKAFKA_C_LIBRARY}
	  )
endif()
add_library(librdkafka-cpp SHARED IMPORTED)
add_library(librdkafka-c SHARED IMPORTED)
set_target_properties(librdkafka-cpp PROPERTIES IMPORTED_LOCATION ${LIBRDKAFKA_CXX_LIBRARY})
set_target_properties(librdkafka-c PROPERTIES IMPORTED_LOCATION ${LIBRDKAFKA_C_LIBRARY})
if (WIN32)
	set_target_properties(librdkafka-cpp PROPERTIES
	  IMPORTED_IMPLIB ${LIBRDKAFKA_CXX_LIBRARY}
	  IMPORTED_IMPLIB_DEBUG ${LIBRDKAFKA_CXX_LIBRARY}
	)
	set_target_properties(librdkafka-c PROPERTIES
	  IMPORTED_IMPLIB ${LIBRDKAFKA_C_LIBRARY}
	  IMPORTED_IMPLIB_DEBUG ${LIBRDKAFKA_C_LIBRARY}
	)
endif()


#set(GOOGLETEST_SOURCE_DIR "${PROJECT_ROOT}/third-party/googletest")
#set(GOOGLETEST_BINARY_DIR "${CMAKE_BINARY_DIR}/googletest")
##set(GOOGLETEST_INSTALL_DIR "${GOOGLETEST_BINARY_DIR}/_install")
#set(GOOGLETEST_INSTALL_DIR ${INSTALL_DIR})
#set(GOOGLETEST_INCLUDE_DIR "${GOOGLETEST_INSTALL_DIR}/include")
#set(GOOGLETEST_LIBRARY_DIR "${GOOGLETEST_INSTALL_DIR}/lib")
#set(GOOGLETEST_LIBRARY "${GOOGLETEST_LIBRARY_DIR}/${LIBRARY_PREFIX}gtest${DYNAMIC_LIBRARY_EXTENSION}")
#set(GOOGLETEST_LIBRARY_WITH_MAIN "${GOOGLETEST_LIBRARY_DIR}/${LIBRARY_PREFIX}gtest_main${DYNAMIC_LIBRARY_EXTENSION}")
#ExternalProject_Add(googletest-module
#  GIT_REPOSITORY "https://github.com/google/googletest"
#  GIT_TAG v1.14.0
#  SOURCE_DIR "${GOOGLETEST_SOURCE_DIR}"
#  BINARY_DIR "${GOOGLETEST_BINARY_DIR}"
#  INSTALL_DIR "${GOOGLETEST_INSTALL_DIR}"
#  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${GOOGLETEST_INSTALL_DIR} -DBUILD_SHARED_LIBS=ON
#  BUILD_BYPRODUCTS ${GOOGLETEST_LIBRARY} ${GOOGLETEST_LIBRARY_WITH_MAIN} ${GOOGLETEST_INCLUDE_DIR}
#  )
#add_library(libgtest STATIC IMPORTED)
#add_library(libgtest-main STATIC IMPORTED)
#
#set_target_properties(libgtest PROPERTIES IMPORTED_LOCATION ${GOOGLETEST_LIBRARY})
#set_target_properties(libgtest-main PROPERTIES IMPORTED_LOCATION ${GOOGLETEST_LIBRARY_WITH_MAIN})
#if (WIN32)
#	set_target_properties(libgtest PROPERTIES
#	  IMPORTED_IMPLIB ${GOOGLETEST_LIBRARY}
#	  IMPORTED_IMPLIB_DEBUG ${GOOGLETEST_LIBRARY}
#	)
#	set_target_properties(libgtest-main PROPERTIES
#	  IMPORTED_IMPLIB ${GOOGLETEST_LIBRARY_WITH_MAIN}
#	  IMPORTED_IMPLIB_DEBUG ${GOOGLETEST_LIBRARY_WITH_MAIN}
#	)
#endif (WIN32)
#
#target_include_directories(libgtest INTERFACE ${GOOGLETEST_INCLUDE_DIR})
#target_include_directories(libgtest-main INTERFACE ${GOOGLETEST_INCLUDE_DIR})
#
#file(MAKE_DIRECTORY ${GOOGLETEST_INCLUDE_DIR})

if(BUILD_TESTING)
  enable_testing()
  include(AddGoogleTest)
endif()



add_subdirectory(libnatkit)
