FROM gcc:14.2-bookworm
WORKDIR /libnatkit

RUN apt update
RUN apt install cmake netcat-openbsd -y

COPY . ./
RUN cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build --parallel 16

CMD sh -c 'echo "Waiting for Kafka..."; \
    while ! nc -z natkit-v0-kafka 9092; do sleep 1; done; \
    echo "Waiting for Mosquitto..."; \
    while ! nc -z mosquitto 1883; do sleep 1; done; \
    echo "Starting bridge..."; \
    exec /libnatkit/build/libnatkit/tools/src/libnatkit-kafka-mosquitto-bridge natkit-v0-kafka:9092 mosquitto:1883'
