#FROM drogonframework/drogon:latest
FROM gcc:14.2-bookworm
WORKDIR /libnatkit

RUN apt update
RUN apt install cmake -y
RUN apt install build-essential -y 
RUN apt install -y libjsoncpp-dev libssl-dev zlib1g-dev libsqlite3-dev uuid-dev
#RUN apt install dos2unix -y

COPY . ./
#RUN find . -type f -print0 | xargs -0 dos2unix
RUN ls /usr/include/jsoncpp/json
RUN ls /usr/local/lib
RUN g++ -xc++ -E -v - < /dev/null
RUN gcc -v -E - < /dev/null 2>&1 | awk '/#include <...> search starts here:/ {f=1; next} /End of search list./ {f=0} f' | xargs ls


RUN cmake -B third-party/drogon/build -S third-party/drogon -DCMAKE_BUILD_TYPE=Release
RUN cmake --build third-party/drogon/build --parallel 16
RUN cmake --install third-party/drogon/build
RUN ln -s /usr/include/jsoncpp/json /usr/include/json

#CMD exec /bin/sh -c "trap : TERM INT; sleep infinity & wait"

RUN cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_NATKIT_BACKEND=ON
RUN cmake --build build --parallel 16
RUN mkdir /cores
RUN mkdir /logs
RUN ulimit -c unlimited

CMD while true; do /libnatkit/build/libnatkit/tools/src/libnatkit-natkit-backend 2>&1 | tee "/logs/log_$(date +'%Y-%m-%d_%H-%M-%S.%3N').log"; sleep 5; done
